<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Keji.Contracts\Keji.Contracts.csproj" />
    <ProjectReference Include="..\Keji.Tools\Keji.Tools.csproj" />
    <ProjectReference Include="..\Keji.Security\Keji.Security.csproj" />
    <ProjectReference Include="..\Keji.Auditing\Keji.Auditing.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
