<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.9" />
    <PackageReference Include="MySqlConnector" Version="2.5.0" />
    <PackageReference Include="Npgsql" Version="10.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Keji.Auditing\Keji.Auditing.csproj" />
    <ProjectReference Include="..\Keji.Providers\Keji.Providers.csproj" />
    <ProjectReference Include="..\Keji.Security\Keji.Security.csproj" />
    <ProjectReference Include="..\Keji.Persistence\Keji.Persistence.csproj" />
  </ItemGroup>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
</Project>
